# Generated by Django 4.2.7 on 2024-06-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
    ]
