# Generated by Django 4.2.7 on 2024-06-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_student_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pic',
        ),
    ]
